--CREATE DATABASE MARKET2
--USE MARKET2

-- TABLES

-- VEZIFE
CREATE TABLE VEZIFE(
ID INT PRIMARY KEY IDENTITY,
AD NVARCHAR(70)
)

-- ISHCI
CREATE TABLE ISHCI(
ID INT PRIMARY KEY IDENTITY,
SAA NVARCHAR(100),
VEZIFEID INT REFERENCES VEZIFE(ID),
MAASH MONEY
)

-- FILIAL
CREATE TABLE FILIAL(
ID INT PRIMARY KEY IDENTITY,
AD NVARCHAR(100)
)

-- MEHSUL
CREATE TABLE MEHSUL(
ID INT PRIMARY KEY IDENTITY,
ALISHQIYMET FLOAT,
SATISHQIYMET FLOAT,
AD NVARCHAR(50)
)

-- SATISH
CREATE TABLE SATISH(
ID INT PRIMARY KEY IDENTITY,
MEHSULID INT REFERENCES MEHSUL(ID),
ISHCIID INT REFERENCES ISHCI(ID),
FILIALID INT REFERENCES FILIAL(ID),
SATISHTARIXI DATE
)

-- INSERTING VALUES

--INSERT INTO VEZIFE VALUES('KASSIR'),('ADMINSTRATOR'),('MUHAFIZE')  
--INSERT INTO ISHCI VALUES ('SAMIR ALIYEV NADIR',1,700),('FERRUX ALIYEV',3,800),('EMIL HACIZADE',2,1200)
--INSERT INTO FILIAL VALUES('YASAMAL'),('KOROGHLU'),('NIZAMI'),('XETAI')'
--INSERT INTO MEHSUL VALUES(2,3,'ALMA'),(1,3,'ARMUD'),(2,5,'QARPIZ'),(2,5,'CIYELEK')
--INSERT INTO SATISH VALUES(2,1,2,'2022-04-21'),(3,2,4,'2022-04-12'),(4,3,4,'2022-04-21'),(2,1,1,'2022-04-02'),
--(3,2,2,'2022-04-17'),(2,1,2,'2022-04-13'),(3,3,4,'2022-04-12'),(3,2,3,'2022-04-11'),(4,3,3,'2022-04-07')


-- SORGULAR

-- SORGU 1
-- 1.Satish cedvelinde ishcilerin,satilan mehsullarin,satisin oldugu filialin,mehsulun alish ve satish qiymeti yazilsin.

--SELECT ISHCI.SAA,MEHSUL.AD,FILIAL.AD,MEHSUL.ALISHQIYMET,MEHSUL.SATISHQIYMET FROM SATISH
--INNER JOIN ISHCI ON SATISH.ISHCIID = ISHCI.ID
--INNER JOIN MEHSUL ON SATISH.MEHSULID = MEHSUL.ID
--INNER JOIN FILIAL ON SATISH.FILIALID = FILIAL.ID


-- SORGU 2
-- 2.Butun satishlarin cemini tap

--SELECT SUM(SATISHQIYMET) AS CEMSATISH FROM SATISH
--INNER JOIN ISHCI ON SATISH.ISHCIID = ISHCI.ID
--INNER JOIN MEHSUL ON SATISH.MEHSULID = MEHSUL.ID
--INNER JOIN FILIAL ON SATISH.FILIALID = FILIAL.ID

-- SORGU 3

--SELECT SUM(SATISHQIYMET) AS SATISHCARIAY FROM SATISH
--INNER JOIN MEHSUL ON SATISH.MEHSULID = MEHSUL.ID
--WHERE MONTH(SATISH.SATISHTARIXI) = MONTH(GETDATE())


-- SORGU 4
-- 4.Her ishcinin satdigi mehsul sayini tap

--SELECT ISHCI.SAA,COUNT(*) FROM SATISH
--INNER JOIN ISHCI ON SATISH.ISHCIID = ISHCI.ID
--WHERE SATISH.ISHCIID = ISHCI.ID
--GROUP BY ISHCI.SAA 


-- SORGU 5
-- 5. Bu gun uzre en cox mehsul satilan filiali tap

SELECT TOP 1 FILIAL.AD,COUNT(MEHSULID) AS 'SOLDPRODUCTS' FROM SATISH
INNER JOIN FILIAL ON SATISH.FILIALID = FILIAL.ID
WHERE DAY(SATISH.SATISHTARIXI) = DAY(GETDATE())
GROUP BY FILIAL.AD


-- SORGU 6
-- 6.Cari ayda en cox satilan mehsulu tap

SELECT TOP 1 MEHSUL.AD , COUNT(MEHSULID) AS 'SOLDPRODUCTS' FROM SATISH
INNER JOIN MEHSUL ON SATISH.MEHSULID = MEHSUL.ID
WHERE MONTH(SATISH.SATISHTARIXI) = MONTH(GETDATE())
GROUP BY MEHSUL.AD
ORDER BY COUNT(MEHSULID) DESC
